package com.softyorch.stroopoverload.domain

import com.softyorch.stroopoverload.R

object AchievementDefinitions {
    val all: List<Achievement> = listOf(
        Achievement(
            id = "first_blood",
            titleRes = R.string.achievement_first_blood_title,
            descriptionRes = R.string.achievement_first_blood_desc,
            rarity = Rarity.COMMON,
            iconEmoji = "⚡",
            xpReward = 250,
        ),
        Achievement(
            id = "ten_games",
            titleRes = R.string.achievement_ten_games_title,
            descriptionRes = R.string.achievement_ten_games_desc,
            rarity = Rarity.COMMON,
            iconEmoji = "🎮",
            xpReward = 500,
        ),
        Achievement(
            id = "twenty_five_games",
            titleRes = R.string.achievement_twenty_five_games_title,
            descriptionRes = R.string.achievement_twenty_five_games_desc,
            rarity = Rarity.UNCOMMON,
            iconEmoji = "👾",
            xpReward = 1000,
        ),
        Achievement(
            id = "fifty_games",
            titleRes = R.string.achievement_fifty_games_title,
            descriptionRes = R.string.achievement_fifty_games_desc,
            rarity = Rarity.UNCOMMON,
            iconEmoji = "🎖️",
            xpReward = 1500,
        ),
        Achievement(
            id = "hundred_games",
            titleRes = R.string.achievement_hundred_games_title,
            descriptionRes = R.string.achievement_hundred_games_desc,
            rarity = Rarity.RARE,
            iconEmoji = "⚔️",
            xpReward = 3000,
        ),
        Achievement(
            id = "two_hundred_games",
            titleRes = R.string.achievement_two_hundred_games_title,
            descriptionRes = R.string.achievement_two_hundred_games_desc,
            rarity = Rarity.EPIC,
            iconEmoji = "🛡️",
            xpReward = 6000,
        ),
        Achievement(
            id = "five_hundred_games",
            titleRes = R.string.achievement_five_hundred_games_title,
            descriptionRes = R.string.achievement_five_hundred_games_desc,
            rarity = Rarity.LEGENDARY,
            iconEmoji = "🌌",
            xpReward = 15000,
        ),
        Achievement(
            id = "five_wins",
            titleRes = R.string.achievement_five_wins_title,
            descriptionRes = R.string.achievement_five_wins_desc,
            rarity = Rarity.COMMON,
            iconEmoji = "🔥",
            xpReward = 500,
        ),
        Achievement(
            id = "fifteen_wins",
            titleRes = R.string.achievement_fifteen_wins_title,
            descriptionRes = R.string.achievement_fifteen_wins_desc,
            rarity = Rarity.UNCOMMON,
            iconEmoji = "💥",
            xpReward = 1200,
        ),
        Achievement(
            id = "thirty_wins",
            titleRes = R.string.achievement_thirty_wins_title,
            descriptionRes = R.string.achievement_thirty_wins_desc,
            rarity = Rarity.UNCOMMON,
            iconEmoji = "🚀",
            xpReward = 2000,
        ),
        Achievement(
            id = "fifty_wins",
            titleRes = R.string.achievement_fifty_wins_title,
            descriptionRes = R.string.achievement_fifty_wins_desc,
            rarity = Rarity.RARE,
            iconEmoji = "🌟",
            xpReward = 4000,
        ),
        Achievement(
            id = "hundred_wins",
            titleRes = R.string.achievement_hundred_wins_title,
            descriptionRes = R.string.achievement_hundred_wins_desc,
            rarity = Rarity.EPIC,
            iconEmoji = "👑",
            xpReward = 8000,
        ),
        Achievement(
            id = "two_hundred_wins",
            titleRes = R.string.achievement_two_hundred_wins_title,
            descriptionRes = R.string.achievement_two_hundred_wins_desc,
            rarity = Rarity.LEGENDARY,
            iconEmoji = "🏆",
            xpReward = 20000,
        ),
        Achievement(
            id = "centurion",
            titleRes = R.string.achievement_centurion_title,
            descriptionRes = R.string.achievement_centurion_desc,
            rarity = Rarity.UNCOMMON,
            iconEmoji = "🎯",
            xpReward = 1000,
        ),
        Achievement(
            id = "score_3k",
            titleRes = R.string.achievement_score_3k_title,
            descriptionRes = R.string.achievement_score_3k_desc,
            rarity = Rarity.RARE,
            iconEmoji = "💎",
            xpReward = 2500,
        ),
        Achievement(
            id = "score_titan",
            titleRes = R.string.achievement_score_titan_title,
            descriptionRes = R.string.achievement_score_titan_desc,
            rarity = Rarity.RARE,
            iconEmoji = "💫",
            hidden = true,
            xpReward = 4500,
        ),
        Achievement(
            id = "score_overlord",
            titleRes = R.string.achievement_score_overlord_title,
            descriptionRes = R.string.achievement_score_overlord_desc,
            rarity = Rarity.EPIC,
            iconEmoji = "🪐",
            hidden = true,
            xpReward = 8000,
        ),
        Achievement(
            id = "score_god",
            titleRes = R.string.achievement_score_god_title,
            descriptionRes = R.string.achievement_score_god_desc,
            rarity = Rarity.LEGENDARY,
            iconEmoji = "🔮",
            hidden = true,
            xpReward = 25000,
        ),
        Achievement(
            id = "flawless",
            titleRes = R.string.achievement_flawless_title,
            descriptionRes = R.string.achievement_flawless_desc,
            rarity = Rarity.UNCOMMON,
            iconEmoji = "✨",
            xpReward = 1000,
        ),
        Achievement(
            id = "flawless_tier2",
            titleRes = R.string.achievement_flawless_tier2_title,
            descriptionRes = R.string.achievement_flawless_tier2_desc,
            rarity = Rarity.RARE,
            iconEmoji = "❄️",
            hidden = true,
            xpReward = 3000,
        ),
        Achievement(
            id = "flawless_tier3",
            titleRes = R.string.achievement_flawless_tier3_title,
            descriptionRes = R.string.achievement_flawless_tier3_desc,
            rarity = Rarity.EPIC,
            iconEmoji = "🧊",
            hidden = true,
            xpReward = 7000,
        ),
        Achievement(
            id = "flawless_tier4",
            titleRes = R.string.achievement_flawless_tier4_title,
            descriptionRes = R.string.achievement_flawless_tier4_desc,
            rarity = Rarity.LEGENDARY,
            iconEmoji = "💠",
            hidden = true,
            xpReward = 18000,
        ),
        Achievement(
            id = "survival_expert",
            titleRes = R.string.achievement_survival_expert_title,
            descriptionRes = R.string.achievement_survival_expert_desc,
            rarity = Rarity.UNCOMMON,
            iconEmoji = "⏱️",
            xpReward = 1200,
        ),
        Achievement(
            id = "survival_master",
            titleRes = R.string.achievement_survival_master_title,
            descriptionRes = R.string.achievement_survival_master_desc,
            rarity = Rarity.RARE,
            iconEmoji = "⌛",
            hidden = true,
            xpReward = 3000,
        ),
        Achievement(
            id = "survival_legend",
            titleRes = R.string.achievement_survival_legend_title,
            descriptionRes = R.string.achievement_survival_legend_desc,
            rarity = Rarity.EPIC,
            iconEmoji = "⏳",
            hidden = true,
            xpReward = 7000,
        ),
        Achievement(
            id = "survival_god",
            titleRes = R.string.achievement_survival_god_title,
            descriptionRes = R.string.achievement_survival_god_desc,
            rarity = Rarity.LEGENDARY,
            iconEmoji = "🕰️",
            hidden = true,
            xpReward = 18000,
        ),
        Achievement(
            id = "streak_master",
            titleRes = R.string.achievement_streak_master_title,
            descriptionRes = R.string.achievement_streak_master_desc,
            rarity = Rarity.UNCOMMON,
            iconEmoji = "🦅",
            xpReward = 1500,
        ),
        Achievement(
            id = "streak_legend",
            titleRes = R.string.achievement_streak_legend_title,
            descriptionRes = R.string.achievement_streak_legend_desc,
            rarity = Rarity.RARE,
            iconEmoji = "🐉",
            xpReward = 4000,
        ),
        Achievement(
            id = "streak_god",
            titleRes = R.string.achievement_streak_god_title,
            descriptionRes = R.string.achievement_streak_god_desc,
            rarity = Rarity.EPIC,
            iconEmoji = "⚡",
            hidden = true,
            xpReward = 9000,
        ),
        Achievement(
            id = "cyber_veteran",
            titleRes = R.string.achievement_cyber_veteran_title,
            descriptionRes = R.string.achievement_cyber_veteran_desc,
            rarity = Rarity.EPIC,
            iconEmoji = "🦾",
            xpReward = 8000,
        ),
    )

    val PREREQUISITES: Map<String, String> = mapOf(
        "twenty_five_games" to "ten_games",
        "fifty_games" to "twenty_five_games",
        "hundred_games" to "fifty_games",
        "two_hundred_games" to "hundred_games",
        "five_hundred_games" to "two_hundred_games",
        "fifteen_wins" to "five_wins",
        "thirty_wins" to "fifteen_wins",
        "fifty_wins" to "thirty_wins",
        "hundred_wins" to "fifty_wins",
        "two_hundred_wins" to "hundred_wins",
        "score_3k" to "centurion",
        "score_titan" to "score_3k",
        "score_overlord" to "score_titan",
        "score_god" to "score_overlord",
        "flawless_tier2" to "flawless",
        "flawless_tier3" to "flawless_tier2",
        "flawless_tier4" to "flawless_tier3",
        "survival_master" to "survival_expert",
        "survival_legend" to "survival_master",
        "survival_god" to "survival_legend",
        "streak_legend" to "streak_master",
        "streak_god" to "streak_legend",
    )
}
