package com.softyorch.stroopoverload.domain

object AchievementDefinitions {
    val all: List<Achievement> = listOf(
        Achievement(
            id = "first_blood",
            titleKey = "NEURAL INITIATION",
            descriptionKey = "Complete a run of at least 5 correct hits.",
            rarity = Rarity.COMMON,
            iconEmoji = "⚡",
            xpReward = 250,
        ),
        Achievement(
            id = "ten_games",
            titleKey = "PILOT CADET",
            descriptionKey = "Play 10 total training runs.",
            rarity = Rarity.COMMON,
            iconEmoji = "🎮",
            xpReward = 500,
        ),
        Achievement(
            id = "twenty_five_games",
            titleKey = "SYNAPTIC TRAINEE",
            descriptionKey = "Play 25 total training runs.",
            rarity = Rarity.UNCOMMON,
            iconEmoji = "👾",
            xpReward = 1000,
        ),
        Achievement(
            id = "fifty_games",
            titleKey = "VETERAN OPERATIVE",
            descriptionKey = "Play 50 total training runs.",
            rarity = Rarity.UNCOMMON,
            iconEmoji = "🎖️",
            xpReward = 1500,
        ),
        Achievement(
            id = "hundred_games",
            titleKey = "NEURAL WARRIOR",
            descriptionKey = "Play 100 total training runs.",
            rarity = Rarity.RARE,
            iconEmoji = "⚔️",
            xpReward = 3000,
        ),
        Achievement(
            id = "two_hundred_games",
            titleKey = "CYBER GUARDIAN",
            descriptionKey = "Play 200 total training runs.",
            rarity = Rarity.EPIC,
            iconEmoji = "🛡️",
            xpReward = 6000,
        ),
        Achievement(
            id = "five_hundred_games",
            titleKey = "SYNAPSE IMMORTAL",
            descriptionKey = "Play 500 total training runs.",
            rarity = Rarity.LEGENDARY,
            iconEmoji = "🌌",
            xpReward = 15000,
        ),
        Achievement(
            id = "five_wins",
            titleKey = "SYNAPSE SPARK",
            descriptionKey = "Win 10 challenge runs.",
            rarity = Rarity.COMMON,
            iconEmoji = "🔥",
            xpReward = 500,
        ),
        Achievement(
            id = "fifteen_wins",
            titleKey = "CORTEX STRIKER",
            descriptionKey = "Win 30 challenge runs.",
            rarity = Rarity.UNCOMMON,
            iconEmoji = "💥",
            xpReward = 1200,
        ),
        Achievement(
            id = "thirty_wins",
            titleKey = "ORBITAL ACE",
            descriptionKey = "Win 60 challenge runs.",
            rarity = Rarity.UNCOMMON,
            iconEmoji = "🚀",
            xpReward = 2000,
        ),
        Achievement(
            id = "fifty_wins",
            titleKey = "NEURAL DOMINATOR",
            descriptionKey = "Win 100 challenge runs.",
            rarity = Rarity.RARE,
            iconEmoji = "🌟",
            xpReward = 4000,
        ),
        Achievement(
            id = "hundred_wins",
            titleKey = "SUPREME COMMANDER",
            descriptionKey = "Win 200 challenge runs.",
            rarity = Rarity.EPIC,
            iconEmoji = "👑",
            xpReward = 8000,
        ),
        Achievement(
            id = "two_hundred_wins",
            titleKey = "GRAND CYBER EMPEROR",
            descriptionKey = "Win 400 challenge runs.",
            rarity = Rarity.LEGENDARY,
            iconEmoji = "🏆",
            xpReward = 20000,
        ),
        Achievement(
            id = "centurion",
            titleKey = "CYBER CENTURION",
            descriptionKey = "Reach a score of 2,500 points in a single run.",
            rarity = Rarity.UNCOMMON,
            iconEmoji = "🎯",
            xpReward = 1000,
        ),
        Achievement(
            id = "score_3k",
            titleKey = "HYPER DRIVER",
            descriptionKey = "Reach a score of 5,000 points in a single run.",
            rarity = Rarity.RARE,
            iconEmoji = "💎",
            xpReward = 2500,
        ),
        Achievement(
            id = "score_titan",
            titleKey = "STROOP OVERLORD",
            descriptionKey = "Score over 7,500 points in a single run.",
            rarity = Rarity.RARE,
            iconEmoji = "💫",
            hidden = true,
            xpReward = 4500,
        ),
        Achievement(
            id = "score_overlord",
            titleKey = "COGNITIVE TITAN",
            descriptionKey = "Score over 10,500 points in a single run.",
            rarity = Rarity.EPIC,
            iconEmoji = "🪐",
            hidden = true,
            xpReward = 8000,
        ),
        Achievement(
            id = "score_god",
            titleKey = "QUANTUM SINGULARITY",
            descriptionKey = "Score over 14,000 points in a single run.",
            rarity = Rarity.LEGENDARY,
            iconEmoji = "🔮",
            hidden = true,
            xpReward = 25000,
        ),
        Achievement(
            id = "flawless",
            titleKey = "SYNAPTIC PURITY",
            descriptionKey = "Achieve 3 flawless runs (5+ rounds, 100% accuracy) in your career.",
            rarity = Rarity.UNCOMMON,
            iconEmoji = "✨",
            xpReward = 1000,
        ),
        Achievement(
            id = "flawless_tier2",
            titleKey = "FLAWLESS EXECUTION",
            descriptionKey = "Achieve 10 flawless runs in your career.",
            rarity = Rarity.RARE,
            iconEmoji = "❄️",
            hidden = true,
            xpReward = 3000,
        ),
        Achievement(
            id = "flawless_tier3",
            titleKey = "PERFECT MIND",
            descriptionKey = "Achieve 30 flawless runs in your career.",
            rarity = Rarity.EPIC,
            iconEmoji = "🧊",
            hidden = true,
            xpReward = 7000,
        ),
        Achievement(
            id = "flawless_tier4",
            titleKey = "ABSOLUTE PRECISION",
            descriptionKey = "Achieve 60 flawless runs in your career.",
            rarity = Rarity.LEGENDARY,
            iconEmoji = "💠",
            hidden = true,
            xpReward = 18000,
        ),
        Achievement(
            id = "survival_expert",
            titleKey = "OVERCLOCK SURVIVOR",
            descriptionKey = "Survive for more than 30 seconds in a single run.",
            rarity = Rarity.UNCOMMON,
            iconEmoji = "⏱️",
            xpReward = 1200,
        ),
        Achievement(
            id = "survival_master",
            titleKey = "TIME WARP",
            descriptionKey = "Survive for more than 50 seconds in a single run.",
            rarity = Rarity.RARE,
            iconEmoji = "⌛",
            hidden = true,
            xpReward = 3000,
        ),
        Achievement(
            id = "survival_legend",
            titleKey = "CHRONO SHIFT",
            descriptionKey = "Survive for more than 75 seconds in a single run.",
            rarity = Rarity.EPIC,
            iconEmoji = "⏳",
            hidden = true,
            xpReward = 7000,
        ),
        Achievement(
            id = "survival_god",
            titleKey = "ETERNAL SYNAPSE",
            descriptionKey = "Survive for more than 100 seconds in a single run.",
            rarity = Rarity.LEGENDARY,
            iconEmoji = "🕰️",
            hidden = true,
            xpReward = 18000,
        ),
        Achievement(
            id = "streak_master",
            titleKey = "MOMENTUM SPARK",
            descriptionKey = "Achieve an 8-game winning streak.",
            rarity = Rarity.UNCOMMON,
            iconEmoji = "🦅",
            xpReward = 1500,
        ),
        Achievement(
            id = "streak_legend",
            titleKey = "UNSTOPPABLE FORCE",
            descriptionKey = "Achieve a 15-game winning streak.",
            rarity = Rarity.RARE,
            iconEmoji = "🐉",
            xpReward = 4000,
        ),
        Achievement(
            id = "streak_god",
            titleKey = "GOD OF SPEED",
            descriptionKey = "Achieve a 25-game winning streak.",
            rarity = Rarity.EPIC,
            iconEmoji = "⚡",
            hidden = true,
            xpReward = 9000,
        ),
        Achievement(
            id = "cyber_veteran",
            titleKey = "CYBERNETIC ELITE",
            descriptionKey = "Win 35 games on Cyber Overload difficulty.",
            rarity = Rarity.EPIC,
            iconEmoji = "🦾",
            xpReward = 8000,
        ),
    )

    val PREREQUISITES: Map<String, String> = mapOf(
        "twenty_five_games" to "ten_games",
        "fifty_games" to "twenty_five_games",
        "hundred_games" to "fifty_games",
        "two_hundred_games" to "hundred_games",
        "five_hundred_games" to "two_hundred_games",
        "fifteen_wins" to "five_wins",
        "thirty_wins" to "fifteen_wins",
        "fifty_wins" to "thirty_wins",
        "hundred_wins" to "fifty_wins",
        "two_hundred_wins" to "hundred_wins",
        "score_3k" to "centurion",
        "score_titan" to "score_3k",
        "score_overlord" to "score_titan",
        "score_god" to "score_overlord",
        "flawless_tier2" to "flawless",
        "flawless_tier3" to "flawless_tier2",
        "flawless_tier4" to "flawless_tier3",
        "survival_master" to "survival_expert",
        "survival_legend" to "survival_master",
        "survival_god" to "survival_legend",
        "streak_legend" to "streak_master",
        "streak_god" to "streak_legend",
    )
}
